name: "Setup canary ndk"
description: "Sets up canary ndk"
outputs:
  ndk-path:
    value: ${{ steps.path.outputs.path }}
    description: "Output path of the ndk"
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}
    description: "Whether a cache hit occurred for the ndk"
runs:
  using: "composite"
  steps:
    - name: NDK cache
      id: cache
      uses: actions/cache@v3
      with:
        path: ${HOME}/android-ndk-r27-canary/
        key: ${{ runner.os }}-ndk-r27-canary

    - name: Download canary ndk
      if: ${{ !steps.cache.outputs.cache-hit }}
      env:
        CANARY_URL: https://dl.google.com/android/repository/android-ndk-r28b-windows.zip
      run: wget ${CANARY_URL} -O ${HOME}/ndk.zip
      shell: bash

    - name: Unzip ndk
      if: ${{ !steps.cache.outputs.cache-hit }}
      run: 7z -snld x "${HOME}/ndk.zip" -o"${HOME}/"
      shell: bash

    - name: Set output
      id: path
      shell: bash
      run: echo "path=${HOME}/android-ndk-r27-canary" >> ${GITHUB_OUTPUT}